In [33]:
import tensorflow as tf 
from transformers import BertTokenizer , TFBertForSequenceClassification

In [34]:
model_name = "bert-base-uncased"   #Load Pretrained model and tokenizer
tokenizer = BertTokenizer.from_pretrained(model_name)
model = TFBertForSequenceClassification.from_pretrained(model_name , num_labels = 2)

All PyTorch model weights were used when initializing TFBertForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [35]:
## Define the text we want to classify
texts = ["This was an amazing product." , "This is not good product to purchase."]

In [36]:
#Tokeinze the text
inputs = tokenizer(texts , return_tensors="tf" , padding=True , truncation=True , max_length= 30)

In [37]:
## Get the model's predictions
outputs = model(inputs)
logits = outputs.logits 

probabilities = tf.nn.softmax(logits , axis =-1)
probabilities

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.53459275, 0.46540722],
       [0.5140604 , 0.48593968]], dtype=float32)>

In [38]:
predictions = tf.argmax(probabilities , axis = -1).numpy()

In [39]:
import numpy as np
np.array(predictions)

array([0, 0], dtype=int64)

In [40]:
## Print out the results
labels = ["Negative" , "Positive"]
for text, prediction in zip(texts,predictions):
    print(f"Text: {text}")
    print(f"Prediction: {labels[prediction]}")

Text: This was an amazing product.
Prediction: Negative
Text: This is not good product to purchase.
Prediction: Negative
